version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/backend/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "back:"
    open-pull-requests-limit: 100
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/frontend/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "front:"
    open-pull-requests-limit: 100
    labels:
      - "dependencies"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
