name: Python style
on: [push, pull_request]
jobs:
  ruff_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with:
          src: './backend'
          args: 'format --preview --check'
