name: Python style
on: [push, pull_request]
jobs:
  ruff_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Sort python imports
        uses: isort/isort-action@v1
        with:
          sort-paths: './backend'
      - name: Show python linter fixes
        uses: chartboost/ruff-action@v1
        with:
          src: './backend'
          args: 'check --fix --diff'
      - name: Show remaining python linter violations
        uses: chartboost/ruff-action@v1
        with:
          src: './backend'
          args: 'check --fix --show-fixes'
      - name: Format Python code
        uses: chartboost/ruff-action@v1
        with:
          src: './backend'
          args: 'format --preview --check --diff'
